### PR TITLE
Implement JNE and JNS functions

### PR DESCRIPTION
**Pull request by dwwmmn**

### CODE REVIEW

**Comment by janbbeck** [comment]
Thanks! do you have a example file that uses these techniques?

**Comment by dwwmmn** [comment]
The binary that inspired this was a RE challenge from the PlaidCTF 2020 which uses a number of simple obfuscation techniques, some more complex than others. You can see a full writeup here: https://medium.com/the-bkpt/plaidctf-2020-reee-80c5cc21ccb1 As the article points out, IDA and binja can detect these useless branches but only Ghidra is smart (bold?) enough to automatically ignore them. Since binja is the only RE tool I'm familiar with I wanted to steal that feature.

I've attached a patched version here. While I don't think it's malicious, a general disclaimer to be safe: it's not my binary, I don't own it, I'm not absolutely confident in what it does and I'm not responsible for anything it does. I wouldn't be surprised if it was flagged as malware by antivirus because of the obfuscated code. If your computer explodes take it up with the PPP :)

When I find more time I'll add the JAE case and any other tricks I can figure out to automate.

[reee.zip](https://github.com/janbbeck/CleanTricks/files/4706724/reee.zip)

**Comment by janbbeck** [comment]
Thanks again. I am trying to replicate. In python 3.8 on windows at least the code crashes, needing a change:

```
def sliding_window(iterable, window_size):
    iterable = iter(iterable) # Thanks for nothing, Python 2
    window = [next(iterable) for _ in range(window_size)]
    while True:
        yield window
        window = window[1:] + [next(iterable)]

```

to
```
def sliding_window(iterable, window_size):
    iterable = iter(iterable) # Thanks for nothing, Python 2
    window = [next(iterable) for _ in range(window_size)]
    while True:
        try:
             yield window
             window = window[1:] + [next(iterable)]
        except StopIteration:
             return
```

the error was like here : https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app

Also, can you share instructions as to how to load oracle.bin into binary ninja at the right address?

**Comment by dwwmmn** [comment]
1. Since my binja was running it as a Python 2 plugin, I didn't test on Python 3. However I now see that the plugin aims to support the most recent versions of both 2 and 3, which means 3.8, so my bad. Testing in a REPL it appears that your suggested fix will work: https://repl.it/repls/EnergeticMonumentalQuotes Can you just modify the PR or should I resubmit?

2. If you are using the oracle.bin from the chal explanation I posted, the first step is to get the dynamically generated code by breaking and dumping the correct section with GDB, as described in the article. From there (or if you're using my binary) an example offset is `0x00400763` for the start of the `JNE` pattern. There are many examples throughout the file in that same area.

**Comment by janbbeck** [comment]
Python 2 is not a target. The developers of BN have been pretty clear that they plan to deprecate it.

I could not get to the archive you linked to. Amazon blocked my region or something.

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>843F392D5D423781</RequestId>
<HostId>
pY9sS9nDPPJsM9v/FjypViOm/3zWOSNo/GgEY9qiQ9Szb+njBnReXU+I3irQUevI1/7vK2CTY5E=
</HostId>
</Error>
```

can you attach an oracle.bin file here for me to load in BN?

Also, I prefer if you just modify the existing PR, but any way you want to do it is fine.

**Comment by dwwmmn** [comment]
Archive with the binary I was using: https://github.com/janbbeck/CleanTricks/files/4706724/reee.zip

**Comment by janbbeck** [comment]
Thanks. I dumped the oracle.bin file as described, but am having problems importing that into BN and get any meaningful decompilation. Does this dump match with yours?:

[oracle.zip](https://github.com/janbbeck/CleanTricks/files/4715338/oracle.zip)

**Comment by dwwmmn** [comment]
The version I uploaded has already been patched by dumping the de-obfuscated section and re-inserting into the binary as described in the article. Just open it and navigate to `0x00400763'. It should look like this screenshot.

**Comment by janbbeck** [comment]
Ah, I get it. Thanks for the PR. Also, thanks for catching the error in the json file.

Merged.

**Comment by dwwmmn** [comment]
Thank you!

**Pull request merged**
